######################################################################
#
# File name : tb_divider_even_wave.do
# Created on: Sun Jan 28 21:16:46 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
