######################################################################
#
# File name : tb_divider_even_simulate.do
# Created on: Sun Jan 28 21:16:46 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_divider_even xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_divider_even_wave.do}

view wave
view structure
view signals

do {tb_divider_even.udo}

run 1000ns
