######################################################################
#
# File name : tb_divider_odd_simulate.do
# Created on: Tue Jan 30 21:53:20 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_divider_odd xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_divider_odd_wave.do}

view wave
view structure
view signals

do {tb_divider_odd.udo}

run 1000ns
