######################################################################
#
# File name : tb_divider_odd_compile.do
# Created on: Tue Jan 30 21:52:40 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../divider_odd.srcs/sources_1/new/divider_odd.v" \
"../../../../divider_odd.srcs/sim_1/new/tb_divider_odd.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

