######################################################################
#
# File name : tb_divider_odd_wave.do
# Created on: Tue Jan 30 21:53:20 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
