######################################################################
#
# File name : tb_mux2_1_wave.do
# Created on: Wed Jul 26 18:41:20 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
