######################################################################
#
# File name : tb_mux2_1_compile.do
# Created on: Sun Jan 21 17:35:07 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\modeltech64_10.4\\win64\\vlib modelsim_lib/work
E:\\modeltech64_10.4\\win64\\vlib modelsim_lib/msim

E:\\modeltech64_10.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_10.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_10.4\\win64\\vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../mux2_1.srcs/sources_1/new/mux2_1.v" \
"../../../../mux2_1.srcs/sim_1/new/tb_mux2_1.v" \


# compile glbl module
E:\\modeltech64_10.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

