######################################################################
#
# File name : tb_mux2_1_simulate.do
# Created on: Sun Jan 21 17:35:10 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_mux2_1 xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_mux2_1_wave.do}

view wave
view structure
view signals

do {tb_mux2_1.udo}

run 1000ns
