######################################################################
#
# File name : tb_decorder_compile.do
# Created on: Sun Jan 21 21:12:45 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\modeltech64_10.4\\win64\\vlib modelsim_lib/work
E:\\modeltech64_10.4\\win64\\vlib modelsim_lib/msim

E:\\modeltech64_10.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_10.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_10.4\\win64\\vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../project_1.srcs/sources_1/new/decorder.v" \
"../../../../project_1.srcs/sim_1/new/tb_decorder.v" \


# compile glbl module
E:\\modeltech64_10.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

