######################################################################
#
# File name : tb_decorder_wave.do
# Created on: Sun Jan 21 20:54:47 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
