######################################################################
#
# File name : tb_half_adder_compile.do
# Created on: Sun Jan 21 21:32:04 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\modeltech64_10.4\\win64\\vlib modelsim_lib/work
E:\\modeltech64_10.4\\win64\\vlib modelsim_lib/msim

E:\\modeltech64_10.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_10.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_10.4\\win64\\vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../half_adder.srcs/sources_1/new/half_adder.v" \
"../../../../half_adder.srcs/sim_1/new/tb_half_adder.v" \


# compile glbl module
E:\\modeltech64_10.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

