######################################################################
#
# File name : tb_half_adder.udo
# Created on: Sun Jan 21 21:26:34 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
