######################################################################
#
# File name : tb_half_adder_wave.do
# Created on: Sun Jan 21 21:26:34 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
