######################################################################
#
# File name : tb_flip_flop_wave.do
# Created on: Tue Jan 23 19:01:49 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
