######################################################################
#
# File name : tb_flip_flop_compile.do
# Created on: Tue Jan 23 19:01:28 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../flip_flop.srcs/sources_1/new/flip_flop.v" \
"../../../../flip_flop.srcs/sim_1/new/tb_flip_flop.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

