######################################################################
#
# File name : tb_full_adder_compile.do
# Created on: Mon Jan 22 18:38:44 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\modeltech64_10.4\\win64\\vlib modelsim_lib/work
E:\\modeltech64_10.4\\win64\\vlib modelsim_lib/msim

E:\\modeltech64_10.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_10.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\modeltech64_10.4\\win64\\vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../full_adder.srcs/sources_1/new/full_adder.v" \
"../../../../full_adder.srcs/sources_1/new/half_adder.v" \
"../../../../full_adder.srcs/sim_1/new/tb_full_adder.v" \


# compile glbl module
E:\\modeltech64_10.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

