######################################################################
#
# File name : tb_full_adder.udo
# Created on: Mon Jan 22 18:18:06 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
