######################################################################
#
# File name : tb_counter_compile.do
# Created on: Thu Jan 25 13:44:38 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../counter.srcs/sources_1/new/counter.v" \
"../../../../counter.srcs/sim_1/new/tb_counter.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

