######################################################################
#
# File name : tb_counter_simulate.do
# Created on: Thu Jan 25 13:44:40 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_counter xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_counter_wave.do}

view wave
view structure
view signals

do {tb_counter.udo}

run 1000ns
