######################################################################
#
# File name : tb_counter_wave.do
# Created on: Thu Jan 25 13:24:34 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
