######################################################################
#
# File name : tb_counter.udo
# Created on: Thu Jan 25 13:24:34 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
